course = 'PyThon For beGinners'
print(course.upper())
print(course.lower())
print(course.find('beGinners'))
print(course.islower())
print(course)
print(course.isupper())
print(course.replace('For','4'))
print(course.rfind('For'))
print('PyThon' in course)